# Job XP Rewards Configuration
# Format: ENTITY_TYPE_NAME: XP_VALUE

hunter-rewards:
  ALLAY: 3
  ARMADILLO: 1
  AXOLOTL: 2
  BAT: 3
  BEE: 1
  BLAZE: 3
  BOGGED: 3
  BREEZE: 5
  CAMEL: 2
  CAT: 1
  CAVE_SPIDER: 3
  CHICKEN: 1
  COD: 1
  COW: 1
  CREEPER: 3
  DOLPHIN: 1
  DONKEY: 1
  DROWNED: 3
  ELDER_GUARDIAN: 25
  ENDER_DRAGON: 1000
  ENDERMAN: 6
  ENDERMITE: 1
  EVOKER: 10
  FOX: 1
  FROG: 1
  GHAST: 4
  GLOW_SQUID: 2
  GOAT: 1
  GUARDIAN: 5
  HOGLIN: 4
  HORSE: 1
  HUSK: 3
  IRON_GOLEM: 3
  LLAMA: 1
  MAGMA_CUBE: 1
  MULE: 1
  MOOSHROOM: 1 # Note: MushroomCow.class is the MOOSHROOM EntityType
  OCELOT: 1
  PANDA: 2
  PARROT: 1
  PHANTOM: 3
  PIG: 1
  ZOMBIFIED_PIGLIN: 3 # Note: PigZombie.class is now ZOMBIFIED_PIGLIN
  PIGLIN: 3
  PIGLIN_BRUTE: 7
  PILLAGER: 4
  POLAR_BEAR: 3
  PUFFERFISH: 1
  RABBIT: 1
  RAVAGER: 15
  SALMON: 1
  SHEEP: 1
  SHULKER: 10
  SILVERFISH: 1
  SKELETON: 3
  SKELETON_HORSE: 5
  SLIME: 2
  SNIFFER: 2
  SPIDER: 2
  SQUID: 1
  STRAY: 3
  STRIDER: 1
  TROPICAL_FISH: 1
  TRADER_LLAMA: 1
  TURTLE: 3
  VEX: 2
  VINDICATOR: 4
  WARDEN: 50
  WITCH: 4
  WITHER: 300
  WITHER_SKELETON: 7
  WOLF: 1
  ZOGLIN: 8
  ZOMBIE: 3
  ZOMBIE_VILLAGER: 2

miner-rewards:
  ANDESITE: 0.5
  TUFF: 0.5
  STONE: 0.3
  DEEPSLATE: 0.5
  SMOOTH_BASALT: 0.4
  CALCITE: 0.4
  GRANITE: 0.4
  DIORITE: 0.4
  COAL_ORE: 0.5
  DEEPSLATE_COAL_ORE: 1.5
  REDSTONE_ORE: 1.0
  DEEPSLATE_REDSTONE_ORE: 1.0
  COPPER_ORE: 0.5
  DEEPSLATE_COPPER_ORE: 0.5
  IRON_ORE: 1.5
  DEEPSLATE_IRON_ORE: 1.5
  GOLD_ORE: 1.5
  DEEPSLATE_GOLD_ORE: 1.5
  LAPIS_ORE: 5.0
  DEEPSLATE_LAPIS_ORE: 5.0
  DIAMOND_ORE: 15.0
  DEEPSLATE_DIAMOND_ORE: 15.0
  EMERALD_ORE: 12.25
  DEEPSLATE_EMERALD_ORE: 12.25
  NETHER_QUARTZ_ORE: 0.75
  NETHERRACK: 0.15
  GLOWSTONE: 0.75
  AMETHYST_BLOCK: 0.5
  BUDDING_AMETHYST: 0.6
  ANCIENT_DEBRIS: 14.0

crop-rewards:
  # Crops
  WHEAT: 0.5
  CARROTS: 0.5
  POTATOES: 0.5
  BEETROOTS: 0.5
  NETHER_WART: 4.0
  MELON: 2.0
  PUMPKIN: 2.0
  COCOA: 0.75
  SUGAR_CANE: 0.5
  CHORUS_FLOWER: 1.5
  # Logs
  OAK_LOG: 0.5
  DARK_OAK_LOG: 0.3
  JUNGLE_LOG: 0.3
  BIRCH_LOG: 0.5
  ACACIA_LOG: 0.5
  SPRUCE_LOG: 0.4
  CHERRY_LOG: 0.5
  MANGROVE_LOG: 0.5
  CRIMSON_STEM: 0.6
  WARPED_STEM: 0.6
  # Leaves
  ACACIA_LEAVES: 0.1
  AZALEA_LEAVES: 0.1
  JUNGLE_LEAVES: 0.1
  OAK_LEAVES: 0.1
  BIRCH_LEAVES: 0.1
  SPRUCE_LEAVES: 0.1
  CHERRY_LEAVES: 0.1
  MANGROVE_LEAVES: 0.1
  DARK_OAK_LEAVES: 0.1
  FLOWERING_AZALEA_LEAVES: 0.1

breed-rewards:
  HORSE: 3.0
  DONKEY: 3.0
  COW: 1.0
  GOAT: 3.0
  MOOSHROOM: 4.0
  SHEEP: 1.0
  PIG: 1.0
  CHICKEN: 0.5
  WOLF: 2.0
  CAT: 2.0
  AXOLOTL: 5.0
  LLAMA: 4.0
  RABBIT: 2.0
  TURTLE: 1.5
  PANDA: 3.0
  FOX: 2.5
  BEE: 2.0
  STRIDER: 5.0
  HOGLIN: 5.0
  FROG: 3.0
  CAMEL: 7.0
  SNIFFER: 10.0